dist: bionic
language: rust
rust:
  - nightly
cache: cargo
env:
  global:
    - NODE_VERSION="v16.11.0"
    - SOLANA_CLI_VERSION="1.8.0"
git:
  submodules: true

jobs:
  include:
      name: Runs the e2e tests
      script:
        - rustup component add rustfmt clippy
        - nvm install $NODE_VERSION
        - sudo apt-get install -y pkg-config build-essential libudev-dev
        - nvm install $NODE_VERSION
        - npm install
        - sudo apt-get install -y pkg-config build-essential libudev-dev
        - sh -c "$(curl -sSfL https://release.solana.com/v${SOLANA_CLI_VERSION}/install)"
        - export PATH="/home/travis/.local/share/solana/install/active_release/bin:$PATH"
        - export NODE_PATH="/home/travis/.nvm/versions/node/v${NODE_VERSION}/lib/node_modules/:$NODE_PATH"
        - yes | solana-keygen new
        - npm i -g @project-serum/anchor-cli
        - anchor test